name: fips

on:
  push:
    branches:
      - '*'
      - '!generate/aws-lc-*'
  pull_request:
    branches:
      - '*'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1
  # We can pin the version if nightly is too unstable.
  # Otherwise, we test against the latest version.
  RUST_NIGHTLY_TOOLCHAIN: nightly
  DEBIAN_FRONTEND: noninteractive

permissions:
  contents: read

jobs:
  fips-test:
    if: github.repository_owner == 'aws'
    name: aws-lc-rs fips-tests
    runs-on: ${{ matrix.os }}
    env:
      CC: clang
      CXX: clang++
    strategy:
      fail-fast: false
      matrix:
        rust: [ stable ]
        os: [ ubuntu-latest, macos-15-intel, macos-latest ]
        args:
          - --release --all-targets --features fips,unstable
          - --profile release-lto --all-targets --features fips,unstable
          - --no-default-features --features fips,unstable
          - --no-default-features --features fips,ring-io,unstable
          - --no-default-features --features fips,ring-sig-verify,unstable
          - --no-default-features --features fips,alloc,unstable
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: 'recursive'
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        id: toolchain
        with:
          toolchain: ${{ matrix.rust }}
      - name: Set Rust toolchain override
        run: rustup override set ${{ steps.toolchain.outputs.name }}
      - uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version: '>=1.18'
      - if: ${{ startsWith( matrix.os, 'macos-') }}
        name: Update Cmake
        # Use latest CMake
        run: |
          brew update
          brew uninstall --force cmake
          brew install --force cmake
          cmake --version
          echo 'CMAKE=${{ (matrix.os == 'macos-15-intel' && '/usr/local') || '/opt/homebrew' }}/bin/cmake' >> $GITHUB_ENV
      - name: Run cargo test
        working-directory: ./aws-lc-rs
        run: cargo test ${{ matrix.args }}
  windows-fips-test:
    if: github.repository_owner == 'aws'
    name: aws-lc-rs windows-fips-tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        args:
          - --all-targets --features fips,unstable
          - --all-targets --features fips,bindgen,unstable
          - --release --all-targets --features fips,unstable
          - --no-default-features --features fips,unstable
          - --no-default-features --features fips,ring-io,unstable
          - --no-default-features --features fips,ring-sig-verify,unstable
          - --no-default-features --features fips,alloc,unstable
    steps:
      - uses: ilammy/setup-nasm@72793074d3c8cdda771dba85f6deafe00623038b # v1.5.2
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: 'recursive'
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        id: toolchain
        with:
          toolchain: stable
      - name: Set Rust toolchain override
        run: rustup override set ${{ steps.toolchain.outputs.name }}
      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@8b297075da4cd2a5f1fd21fe011b499edf06e9d2 # v4
      - name: Run cargo test
        working-directory: ./aws-lc-rs
        run: cargo test ${{ matrix.args }}
  cpu-jitter-entropy-test:
    if: github.repository_owner == 'aws'
    name: CPU Jitter Entropy Tests
    runs-on: ubuntu-latest
    env:
      AWS_LC_FIPS_SYS_CPU_JITTER_ENTROPY: 1
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: 'recursive'
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        id: toolchain
        with:
          toolchain: nightly
      - uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version: '>=1.18'
      - name: Run assert script
        run: ./scripts/tests/assert_cpu_jitter_entropy.rs
